version: "3.9"

services:
  db-dev:
    extends:
      file: docker-compose.yml
      service: db
    env_file: .db-dev.env
    ports:
      - 5432:5432
    networks:
      - backend-dev

  migration-dev:
    depends_on:
      db-dev:
        condition: service_healthy
    extends:
      file: docker-compose.yml
      service: migration
    env_file: .db-dev.env
    networks:
      - backend-dev

  mock-redis-dev:
    extends:
      file: docker-compose.yml
      service: mock-redis
    ports:
      - 6379:6379
    networks:
      - backend-dev

  mock-notifier-dev:
    extends:
      file: docker-compose.yml
      service: mock-notifier
    depends_on:
      - mock-redis-dev
    env_file: .mock-notifier-dev.env
    networks:
      - backend-dev

networks:
  backend-dev:
    external: true
    name: auction_backend-dev
